---
title: "Description"
author: "Pedro Jesus"
output:

runtime: shiny
---


## Overview

The goal of this app is to show the Central Limit Theorem in action for the exponential distribution. 

## Theory

Central Limit Theorem states that the distribution of the mean of N exponential distributions (or any kind of distribution) gets closer to a normal distribution as N increases. This normal distribution will have the same mean as the original distribution and standard deviation equal to the original standard deviation divided by square root of N.

In the case of the exponential distribution with parameter L, where mean = sd = 1/L, the normal distribution will have mean 1/L and a standard deviation of 1/(sqrt(N)L).

## App description

The user can control 3 values: L, N and the number of simulations.

Given the value of L and N and pressing the "Compute!" button, 2500 means of N exponential distributions with that value of L are computed and stored.

Then given the number of simulations s, s means are chosen from the 2500 and a histogram based on those means is plotted, alongside a red line representing the theoretical normal distribution from the Central Limit Theorem. Also the mean and sd of those means are computed and put on a table next to its theoretical values.

You should see that the histogram gets closer to the red line as the number of simulations increase, the same happening with the mean and sd.